owner: BrickStreet
repo: monitoring

assignees:
  - RoyalMist

sites:
  - name: Estimeight
    url: https://app.brickstreet.ch

status-website:
  cname: up.brickstreet.ch
  theme: night
  name: Monitoring
  introTitle: "**Brickstreet**, estimations the right way."
  introMessage: The status of our services are updated every 5 minutes and reflected here each day.
  navbar:
    - title: Status
      href: /
    - title: Site
      href: https://app.brickstreet.ch
